### ISSUE TITLE
keys.py is not available

### ISSUE THREAD

**Issue by karopass** [gentoo-root/telegram-tracker#1]
Hi!
I am interested in this awesome work but I am not able to find keys.py file in settings directory. Let me know if there something wrong.
Thanks

**Comment by gentoo-root** [comment]
Hi!

Please read the "How to run" section of README.md. The paragraph starting with "Then you need to register your Telegram application on the Telegram website" explains how to acquire API_ID and API_HASH and put them into settings/keys.py. The link to the Telegram website is also in the README.

Basically you need your own keys to gain the same level of access to Telegram as you have when you log in with your credentials. The procedure is easy and needs to be done only once. Please also note that you shouldn't share your API keys with others as well as you shouldn't share your login and password.

**Comment by karopass** [comment]
@gentoo-root 
I know it but I am asking that there no any files called keys.py in settings directory. Where I should put my keys?
Thanks

**Comment by gentoo-root** [comment]
settings/keys.py doesn't exist by default. You need to create it yourself and put your keys there like in the example in README.
