### ISSUE TITLE
Track Multiple Numbers

### ISSUE THREAD

**Issue by karopass** [gentoo-root/telegram-tracker#2]
Hi!
Its working fine. Thanks for nice work. I am able to track one number for now. Can I know How can I track multiple numbers?
Thanks

**Comment by gentoo-root** [comment]
All you need is to launch multiple instances of the tracker, they won't interfere with one another.

I use instantiated systemd services for that (those ones that contain `@` in their names), but you can use any way that's convenient to you. The easiest way is to open multiple terminal windows and to start several instances in different windows.
