### ISSUE TITLE
Output

### ISSUE THREAD

**Issue by lagodich94** [gentoo-root/telegram-tracker#7]
Hi, I try to run your script on Windows 10 PC: open cmd in scrip folder -> run this command (python3 -m track '+xxxxxxxxxxxx') but where I could find log file with data?

**Comment by gentoo-root** [comment]
You should see the log right in your cmd window. If you want to store the output in a file, you can use shell redirection:

    python3 -m track '+xxxxxxxxxxxx' > filename.log
