### ISSUE TITLE
Multitrack

### ISSUE THREAD

**Issue by matteocef** [gentoo-root/telegram-tracker#9]
hello, is it possible to track multiple numbers?

**Comment by Morteza-Gh-Kh** [comment]
Hi,
I think so. It can be done just by putting another loop, e.g. For Loop, inside that While which goes through different contact_ids you've provided.

**Comment by gentoo-root** [comment]
Yes, it's possible. There is no need to modify the script, you can simply run it multiple times in different terminals.
